import mongoose from "mongoose";

export default new mongoose.Schema({
  '': String,
  ID: String,
  Name: String,
  Age: String,
  Photo: String,
  Nationality: String,
  Flag: String,
  Overall: String,
  Potential: String,
  Club: String,
  'Club Logo': String,
  Value: String,
  Wage: String,
  Special: String,
  'Preferred Foot': String,
  'International Reputation': String,
  'Weak Foot':String,
  'Skill Moves': String,
  'Work Rate': String,
  'Body Type': String,
  'Real Face': String,
  Position: String,
  'Jersey Number': String,
  Joined: String,
  'Loaned From': String,
  'Contract Valid Until': String,
  Height: String,
  Weight: String,
  LS: String,
  ST: String,
  RS: String,
  LW: String,
  LF: String,
  CF: String,
  RF: String,
  RW: String,
  LAM: String,
  CAM: String,
  RAM: String,
  LM: String,
  LCM: String,
  CM: String,
  RCM: String,
  RM: String,
  LWB: String,
  LDM: String,
  CDM: String,
  RDM: String,
  RWB: String,
  LB: String,
  LCB: String,
  CB: String,
  RCB: String,
  RB: String,
  Crossing: String,
  Finishing: String,
  HeadingAccuracy: String,
  ShortPassing: String,
  Volleys: String,
  Dribbling: String,
  Curve: String,
  FKAccuracy: String,
  LongPassing: String,
  BallControl: String,
  Acceleration: String,
  SprintSpeed: String,
  Agility: String,
  Reactions: String,
  Balance: String,
  ShotPower: String,
  Jumping: String,
  Stamina: String,
  Strength: String,
  LongShots: String,
  Aggression: String,
  Interceptions: String,
  Positioning: String,
  Vision: String,
  Penalties: String,
  Composure: String,
  Marking: String,
  StandingTackle: String,
  SlidingTackle: String,
  GKDiving: String,
  GKHandling: String,
  GKKicking: String,
  GKPositioning: String,
  GKReflexes: String,
  'Release Clause': String
});


